-- =====================================================================
-- MIGRATION 2026 — Lookbook + Khuyến mãi/Giảm giá
-- Chạy toàn bộ file này 1 lần trong Supabase → SQL Editor → Run.
-- Tất cả câu lệnh đều idempotent (chạy lại nhiều lần không lỗi).
-- =====================================================================

-- ------------------------------------------------------------------
-- 1) LOOKBOOK (trang editorial /lookbook)
--    block_type: 'full' (ảnh/video tràn viền) | 'compare' (slider 2 ảnh) | 'quote' (câu trích dẫn)
-- ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.content_lookbook (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    caption text,
    image_url text,
    image_url_2 text,
    display_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    block_type text DEFAULT 'full',
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.content_lookbook ADD COLUMN IF NOT EXISTS image_url_2 text;
ALTER TABLE public.content_lookbook ADD COLUMN IF NOT EXISTS block_type text DEFAULT 'full';
-- Khối "quote" không cần ảnh nên bỏ ràng buộc NOT NULL của image_url (nếu có)
ALTER TABLE public.content_lookbook ALTER COLUMN image_url DROP NOT NULL;

ALTER TABLE public.content_lookbook ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read Lookbook" ON public.content_lookbook;
CREATE POLICY "Public Read Lookbook" ON public.content_lookbook FOR SELECT USING (true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.content_lookbook TO service_role;
GRANT SELECT ON TABLE public.content_lookbook TO anon;
GRANT SELECT ON TABLE public.content_lookbook TO authenticated;

-- ------------------------------------------------------------------
-- 2) GIẢM GIÁ TRỰC TIẾP theo số tiền cho từng sản phẩm
--    (giá gốc vẫn là base_price; discount_amount = số tiền giảm; bật/tắt bằng is_discount_active)
-- ------------------------------------------------------------------
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS discount_amount numeric(12,0) DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_discount_active boolean DEFAULT false;

-- ------------------------------------------------------------------
-- 3) VOUCHER áp dụng cho SẢN PHẨM CỤ THỂ + không giới hạn số lượng/thời gian
--    applicable_product_ids: mảng id sản phẩm ('[]' = áp cho tất cả)
--    usage_limit / start_date / end_date = NULL nghĩa là không giới hạn
-- ------------------------------------------------------------------
ALTER TABLE public.promotions ADD COLUMN IF NOT EXISTS applicable_product_ids jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.promotions ALTER COLUMN usage_limit DROP NOT NULL;
-- start_date, end_date vốn đã nullable.

-- ------------------------------------------------------------------
-- 4) Buộc PostgREST nạp lại schema cache để nhận cột mới ngay
-- ------------------------------------------------------------------
NOTIFY pgrst, 'reload schema';
