-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;
-- GRANT ALL ON SCHEMA public TO postgres;
-- GRANT ALL ON SCHEMA public TO public;

-- =============================================
-- PHẦN 1: CẤU HÌNH CƠ BẢN & CÁC BẢNG DANH MỤC
-- =============================================

-- 1. Bảng Chi nhánh (Kho hàng)
CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- VD: Kho Tổng, Cửa hàng Q1
    address TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Bảng Danh mục Sản phẩm (Hỗ trợ danh mục cha/con)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL, -- URL thân thiện
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL, -- Danh mục cha
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Bảng Nhà cung cấp
CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT, -- JSON hoặc Text
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =============================================
-- PHẦN 2: SẢN PHẨM & BIẾN THỂ
-- =============================================

-- 4. Bảng Sản phẩm (Thông tin chung)
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    base_price DECIMAL(12,0) NOT NULL, -- Giá niêm yết cơ bản
    images TEXT[], -- Mảng link ảnh
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Bảng Trung gian: Sản phẩm - Danh mục (Một áo thuộc nhiều danh mục)
CREATE TABLE product_categories (
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, category_id)
);

-- 6. Bảng Biến thể (SKU) - Chi tiết từng size/màu
CREATE TABLE variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    sku TEXT UNIQUE NOT NULL, -- Mã vạch (Barcode)
    size TEXT NOT NULL,
    color TEXT NOT NULL,
    current_price DECIMAL(12,0), -- Nếu null thì lấy base_price của products
    image_url TEXT, -- Ảnh riêng cho biến thể màu này (nếu có)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- PHẦN 3: KHO HÀNG FIFO (TRÁI TIM CỦA HỆ THỐNG)
-- =============================================

-- 7. Bảng Phiếu Nhập kho
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES suppliers(id),
    store_id BIGINT REFERENCES stores(id),
    total_cost DECIMAL(12,0) NOT NULL DEFAULT 0,
    note TEXT,
    purchase_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Bảng Chi tiết nhập kho
CREATE TABLE purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT REFERENCES purchase_orders(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES variants(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_cost DECIMAL(12,0) NOT NULL -- Giá vốn lúc nhập
);

-- 9. Bảng Lô hàng tồn kho (Inventory Batches) - Dùng để tính FIFO
-- Mỗi lần nhập hàng sẽ tạo ra một "Batch" mới tại đây. Khi bán sẽ trừ dần batch cũ nhất.
CREATE TABLE inventory_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES stores(id),
    variant_id BIGINT REFERENCES variants(id),
    purchase_item_id BIGINT REFERENCES purchase_items(id), -- Link tới phiếu nhập gốc
    original_quantity INTEGER NOT NULL, -- Số lượng ban đầu
    quantity_remaining INTEGER NOT NULL CHECK (quantity_remaining >= 0), -- Số còn lại
    cost_price DECIMAL(12,0) NOT NULL, -- Giá vốn lô này
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() -- Quan trọng để sort FIFO
);

-- 1. Thêm cột tên lô hàng (để lưu mã PO-...)
ALTER TABLE inventory_batches 
ADD COLUMN batch_name TEXT;

-- 2. Thêm cột nhà cung cấp (để biết lô này nhập của ai)
ALTER TABLE inventory_batches 
ADD COLUMN supplier_id BIGINT REFERENCES suppliers(id);

-- Index để tìm kiếm tồn kho nhanh hơn
CREATE INDEX idx_inventory_fifo ON inventory_batches (store_id, variant_id, created_at ASC);

-- =============================================
-- PHẦN 4: KHÁCH HÀNG & KHUYẾN MÃI
-- =============================================

-- 10. Bảng Khách hàng
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID, -- Link tới Supabase Auth (NULL nếu là khách vãng lai)
    full_name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address TEXT,
    loyalty_points INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Index số điện thoại để tra cứu nhanh khách vãng lai
CREATE INDEX idx_customer_phone ON customers (phone);

-- 11. Bảng Khuyến mãi (Voucher)
CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    description TEXT,
    discount_type TEXT CHECK (discount_type IN ('percent', 'fixed')), -- % hoặc trừ tiền thẳng
    discount_value DECIMAL(12,0) NOT NULL,
    min_order_value DECIMAL(12,0) DEFAULT 0,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    requires_account BOOLEAN DEFAULT TRUE, -- True: Phải đăng nhập mới dùng đc
    is_active BOOLEAN DEFAULT TRUE
);

-- 12. Bảng Giỏ hàng (Chỉ dành cho khách đã đăng nhập)
CREATE TABLE carts (
    user_id UUID PRIMARY KEY, -- Một user chỉ có 1 giỏ hàng active
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id UUID REFERENCES carts(user_id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES variants(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);

-- =============================================
-- PHẦN 5: BÁN HÀNG (SALES)
-- =============================================

-- 13. Bảng Đơn hàng
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL, -- Mã đơn hàng (VD: ORD-2025-001)
    customer_id BIGINT REFERENCES customers(id),
    store_id BIGINT REFERENCES stores(id), -- Đơn này thuộc kho nào
    promotion_id BIGINT REFERENCES promotions(id),
    
    -- Các cột tiền
    subtotal DECIMAL(12,0) NOT NULL, -- Tiền hàng
    discount_amount DECIMAL(12,0) DEFAULT 0, -- Tiền giảm giá
    shipping_fee DECIMAL(12,0) DEFAULT 0, -- Phí ship
    total_amount DECIMAL(12,0) NOT NULL, -- Khách phải trả (Sub - Disc + Ship)
    
    payment_method TEXT DEFAULT 'cod', -- cod, banking
    status TEXT DEFAULT 'pending', -- pending, confirmed, shipping, completed, cancelled, returned
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1. Thêm cột lưu thông tin người nhận (quan trọng cho đơn hàng vãng lai)
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS customer_name TEXT,
ADD COLUMN IF NOT EXISTS customer_phone TEXT,
ADD COLUMN IF NOT EXISTS customer_address TEXT,
ADD COLUMN IF NOT EXISTS customer_email TEXT;

-- 2. Cho phép store_id null (vì mua online chưa chắc đã assign ngay cho kho nào)
ALTER TABLE orders 
ALTER COLUMN store_id DROP NOT NULL;

-- 14. Bảng Chi tiết đơn hàng
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    variant_id BIGINT REFERENCES variants(id),
    quantity INTEGER NOT NULL,
    price_at_purchase DECIMAL(12,0) NOT NULL, -- Giá bán cho khách lúc đó
    cogs_total DECIMAL(12,0) DEFAULT 0 -- Tổng giá vốn của dòng này (Tính bằng FIFO logic sau khi bán)
);

-- =============================================
-- PHẦN 6: TÀI CHÍNH (FINANCE)
-- =============================================

-- 15. Danh mục chi phí
CREATE TABLE expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- Quảng cáo, Thuê mặt bằng, Lương...
    description TEXT
);

-- 16. Phiếu chi
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES stores(id),
    category_id BIGINT REFERENCES expense_categories(id),
    amount DECIMAL(12,0) NOT NULL,
    expense_date DATE DEFAULT CURRENT_DATE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 1. Cấp quyền sử dụng Schema 'public' cho các vai trò
GRANT USAGE ON SCHEMA public TO postgres, anon, service_role;

-- 2. Cấp quyền TOÀN BỘ cho Admin (service_role) và Postgres
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO postgres, service_role;

-- 3. Cấp quyền XEM (SELECT) cho khách vãng lai (anon) - Quan trọng cho Web
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;

-- Xóa dữ liệu cũ và reset ID về 1
TRUNCATE TABLE 
    inventory_batches, purchase_items, purchase_orders, 
    order_items, orders, cart_items, carts, 
    variants, product_categories, products, 
    suppliers, categories, stores, customers, promotions 
    RESTART IDENTITY CASCADE;

-- 1. TẠO CHI NHÁNH (STORES)
INSERT INTO stores (name, address, phone) VALUES 
('Kho Tổng Hà Nội', '123 Cầu Giấy, Hà Nội', '0901234567'),
('Cửa hàng Quận 1', '45 Nguyễn Huệ, TP.HCM', '0909999888');

-- 2. TẠO DANH MỤC (CATEGORIES)
INSERT INTO categories (name, slug) VALUES 
('Áo thun','ao-thun'),
('Váy Đầm', 'vay-dam'),
('Áo Sơ Mi', 'ao-so-mi'),
('Quần Tây', 'quan-tay'),
('Áo Khoác', 'ao-khoac');


-- 3. TẠO NHÀ CUNG CẤP (SUPPLIERS)

-- Thêm dữ liệu mẫu vào bảng suppliers (cấu trúc mới)
INSERT INTO suppliers (name, address, phone) 
VALUES ('Kho Vải Ninh Hiệp', 'Ninh Hiệp, Gia Lâm, Hà Nội', '0988123123');

INSERT INTO suppliers (name, address, phone) 
VALUES ('Xưởng May Gia Công A', 'Quận 12, TP.HCM', '0909000111');
-- 4. TẠO SẢN PHẨM (PRODUCTS)
INSERT INTO products (name, slug, description, base_price, images) VALUES 
('Đầm Lụa Tơ Tằm Cổ Đổ', 'dam-lua-to-tam', 'Chất liệu lụa cao cấp, sang trọng.', 1200000, ARRAY['https://via.placeholder.com/500x750?text=Dam+Lua']),
('Áo Sơ Mi Lụa Basic', 'ao-so-mi-lua', 'Thiết kế tối giản, phù hợp công sở.', 650000, ARRAY['https://via.placeholder.com/500x750?text=Ao+So+Mi']);

-- Link sản phẩm vào danh mục
INSERT INTO product_categories (product_id, category_id) VALUES 
(1, 1), -- Đầm lụa thuộc Váy Đầm
(2, 2); -- Áo sơ mi thuộc Áo Sơ Mi

-- 5. TẠO BIẾN THỂ (VARIANTS)
-- ID 1: Đầm Lụa - Size S - Trắng
INSERT INTO variants (product_id, sku, size, color, current_price) VALUES 
(1, 'DL-W-S', 'S', 'Trắng', 1200000),
(1, 'DL-W-M', 'M', 'Trắng', 1200000),
(1, 'DL-B-S', 'S', 'Đen', 1200000);

-- ID 4: Áo Sơ Mi - Size S - Be
INSERT INTO variants (product_id, sku, size, color, current_price) VALUES 
(2, 'ASM-BE-S', 'S', 'Be', 650000),
(2, 'ASM-BE-M', 'M', 'Be', 650000);

-- 6. TẠO PHIẾU NHẬP (PURCHASE ORDERS)
-- Nhập lần 1: Nhập về Kho Tổng
INSERT INTO purchase_orders (supplier_id, store_id, total_cost, note, purchase_date) VALUES 
(1, 1, 50000000, 'Nhập hàng vụ Thu Đông đợt 1', NOW() - INTERVAL '10 days');

-- 7. TẠO CHI TIẾT NHẬP (PURCHASE ITEMS)
-- Nhập 10 cái Đầm Lụa Size S (Variant ID 1) giá vốn 500k
INSERT INTO purchase_items (purchase_order_id, variant_id, quantity, unit_cost) VALUES 
(1, 1, 10, 500000); 
-- Nhập 10 cái Áo Sơ Mi Size S (Variant ID 4) giá vốn 250k
INSERT INTO purchase_items (purchase_order_id, variant_id, quantity, unit_cost) VALUES 
(1, 4, 10, 250000);

-- 8. TẠO LÔ HÀNG TỒN KHO (INVENTORY BATCHES) - QUAN TRỌNG
-- Hệ thống tự động ánh xạ từ Purchase Items sang đây để quản lý FIFO
-- Lô 1: Đầm Lụa Size S tại Kho Tổng, còn nguyên 10 cái, giá vốn 500k
INSERT INTO inventory_batches (store_id, variant_id, purchase_item_id, original_quantity, quantity_remaining, cost_price, created_at) VALUES 
(1, 1, 1, 10, 10, 500000, NOW() - INTERVAL '10 days');

-- Lô 2: Áo Sơ Mi Size S tại Kho Tổng, còn nguyên 10 cái, giá vốn 250k
INSERT INTO inventory_batches (store_id, variant_id, purchase_item_id, original_quantity, quantity_remaining, cost_price, created_at) VALUES 
(1, 4, 2, 10, 10, 250000, NOW() - INTERVAL '10 days');

-- Giả lập thêm 1 Lô nhập sau (giá vốn tăng lên) cho Đầm Lụa Size S để test FIFO sau này
-- Nhập thêm 5 cái giá 550k (đắt hơn lô trước 50k)
INSERT INTO inventory_batches (store_id, variant_id, purchase_item_id, original_quantity, quantity_remaining, cost_price, created_at) VALUES 
(1, 1, NULL, 5, 5, 550000, NOW());